import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Listvin — Know exactly what to make next",
  description: "Listvin gives creators AI-powered content briefs. Analyse your history across YouTube and TikTok, understand what works, and get your weekly content brief — generated by AI.",
  other: {
    "tiktok-developers-site-verification": "mjAumAcJpBEQruZMcU5TVht15CVMFOex",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full`}>
      <body className="min-h-full bg-[--background] text-[--foreground] antialiased">
        {children}
      </body>
    </html>
  );
}
