import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CreatorIQ — Know exactly what to make next",
  description: "AI-powered content briefs for YouTube creators. Analyse your channel, understand what works, and get your weekly content brief — generated by AI.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full`}>
      <body className="min-h-full bg-[--background] text-[--foreground] antialiased">
        {children}
      </body>
    </html>
  );
}
